// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesWorkshop.Data.Context;

#nullable disable

namespace MoviesWorkshop.Migrations
{
    [DbContext(typeof(MovieAppContext))]
    partial class MovieAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoviesWorkshop.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("nvarchar(127)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A young hobbit, Frodo, who has found the One Ring that belongs to the Dark Lord Sauron, begins his journey with eight companions to Mount Doom, the only place where it can be destroyed.",
                            Genre = 2,
                            Title = "The Lord of the Rings: The fellowship of the ring",
                            Year = 2001
                        },
                        new
                        {
                            Id = 2,
                            Description = "A young boy, Harry Potter, discovers he is a wizard and embarks on a journey to Hogwarts School of Witchcraft and Wizardry, where he learns about his past and confronts the dark wizard who killed his parents.",
                            Genre = 7,
                            Title = "Harry Potter and the Sorcerer's Stone",
                            Year = 2001
                        },
                        new
                        {
                            Id = 3,
                            Description = "A wealthy entrepreneur creates a theme park where genetically-engineered dinosaurs roam. Chaos ensues when the dinosaurs break free, and a group of people must survive the dangerous creatures.",
                            Genre = 11,
                            Title = "Jurassic Park",
                            Year = 1993
                        },
                        new
                        {
                            Id = 4,
                            Description = "Dom Cobb is a skilled thief who enters people's dreams to steal their deepest secrets. He is given a challenging task - to plant an idea into someone's mind through a complex process of dream manipulation.",
                            Genre = 11,
                            Title = "Inception",
                            Year = 2010
                        },
                        new
                        {
                            Id = 5,
                            Description = "A group of superheroes, including Iron Man, Thor, Captain America, Hulk, Black Widow, and Hawkeye, join forces to stop Loki and his alien army from taking over Earth.",
                            Genre = 1,
                            Title = "The Avengers",
                            Year = 2012
                        },
                        new
                        {
                            Id = 6,
                            Description = "A clownfish named Marlin embarks on a journey across the ocean to find his son, Nemo, who has been captured by a diver and placed in a fish tank in a dentist's office.",
                            Genre = 3,
                            Title = "Finding Nemo",
                            Year = 2003
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
